name: 'Cloudflared Remote Server SSH Commands'
branding:
  icon: 'terminal'
  color: 'orange'
description: 'Lets you SSH into a server behind a Cloudflare tunnel'
inputs:
  host:
    description: 'SSH host address'
    required: true
  port:
    description: 'SSH port number'
    default: "22"
  username:
    description: 'SSH username'
  private_key:
    description: 'SSH private key'
  commands:
    description: 'The commands to run on the remote server'
  service_token_id:
    description: 'The Client ID of the Cloudflare service token'
  service_token_id:
    description: 'The Client Secret of the Cloudflare service token'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}
    - ${{ inputs.port }}
    - ${{ inputs.username }}
    - ${{ inputs.private_key }}
    - ${{ inputs.commands }}
    - ${{ inputs.service_token_id }}
    - ${{ inputs.service_token_secret }}
