name: "Automatic release"
on:
  push:
    branches:
      - main

jobs:
  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Release latest build
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest build"